export const ingredient = [
    "white balsamic vinegar",
    "lemon juice",
    "lemon rind",
    "red chillies",
    "garlic cloves (crushed)",
    "olive oil",
    "summer squash (zucchini)",
    "sea salt",
    "black pepper",
    "basil leaves",
    "chicken mince",
    "garlic (minced)",
    "onion",
    "salt",
    "carrot",
    "cabbage",
    "green onions",
    "sweet chilli sauce",
    "peanut butter",
    "ginger",
    "soy sauce",
    "fresh cilantro",
    "red pepper flakes (crushed)",
    "tarts",
    "almonds whole",
    "egg white",
    "curry leaves",
    "sugar (fine grain)",
    "red chilli powder",
    "vinegar",
    "honey/sugar",
    "garlic cloves (minced)",
    "chilli pepper (sliced)",
    "green papaya",
    "carrot (peeled)",
    "cucumbers",
    "mint leaves",
    "toasted peanuts",
    "christmas dry fruits (pre-soaked)",
    "orange zest",
    "lemon zest",
    "jaggery syrup",
    "almond flour",
    "apple",
    "butter (softened)",
    "eggs",
    "japanese curry",
    "sticky rice",
    "cheese inside rice",
    "barley salsa",
    "wasabi mayo",
    "red capsicum cube (cut)",
    "yellow capsicum cube (cut)",
    "green capsicum cube (cut)",
    "green chili",
    "barley",
    "butter",
    "white pepper",
    "light soya",
    "almonds",
    "granulated sugar",
    "bittersweet chocolate",
    "unsalted butter",
    "flour",
    "baking powder",
    "castor sugar",
    "icing sugar",
    "lamb bones (preferably shank and shoulder)",
    "onions",
    "celery",
    "garlic",
    "chargrilled red/yellow/green bell peppers (quartered)",
    "whole spices mix (black pepper",
    "cinnamon",
    "cardamom",
    "clove",
    "bay leaf)",
    "water (warm)",
    "oil (sunflower or olive",
    "vegetable stock",
    "skimmed milk",
    "toasted almonds (powdered)",
    "salt and pepper",
    "nutmeg",
    "almond essence",
    "toasted almond flakes",
    "broccoli",
    "ground almonds (toasted)",
    "freshly ground black pepper",
    "uncooked quinoa",
    "water",
    "red onion",
    "cucumber (diced)",
    "purple cabbage",
    "avocado (ripened and diced) ",
    "orange",
    "shelled edamame(defrosted)",
    "unsweetened toasted coconut flakes",
    "few shakes of black pepper",
    "for the dressing: ",
    "orange juice",
    "lime(juiced)",
    "apple cider vinegar",
    "young corn on the cob",
    "honey",
    "garlic cloves(smashed)",
    "celery stalk",
    "chives",
    "paprika powder",
    "parsley",
    "plastic bag",
    "food thermometer",
    "fresh strawberries",
    "low fat yogurt",
    "watermelon",
    "chia seeds",
    "fresh raspberries",
    "ripe banana",
    "almond",
    "fresh peach slices",
    "fresh raspberry",
    "peach fruit slices",
    "almond flakes",
    "poha",
    "cranberries(frozen / dried)",
    "oil",
    "green chilies",
    "fresh coconut",
    "almond slivers",
    "raw banana(boiled)",
    "almond paste",
    "cooking cream",
    "refined oil",
    "mace powder",
    "cardamom powder",
    "ginger garlic paste",
    "garam masala powder",
    "tempura batter",
    "almonds(crushed)",
    "tomato",
    "garlic cloves",
    "basil sprig",
    "lemon",
    "pepper",
    "for namak para: ",
    "refined flour",
    "sugar",
    "khoya",
    "sweetener(optional)",
    "whole wheat flour(atta)",
    "refined flour(maida)",
    "chaat masala",
    "cumin powder",
    "tomato puree",
    "ghee",
    "oats",
    "ragi flour(bhakri atta)",
    "wheat flour",
    "rice flour",
    "urad dal flour(dry roast and grind the dal to a fine powder)",
    "cumin seeds",
    "green chillies",
    "apples",
    "milk",
    "green cardamoms",
    "almonds(blanched)",
    "pistachios(blanched)",
    "carom seeds(ajwain)",
    "dates(pitted)",
    "mixed nuts(almonds",
    "cashews",
    "walnuts",
    "pistachios",
    "peanuts)",
    "dessicated coconut(optional)",
    "whole moong beans",
    "cow ghee",
    "raisins",
    "whole milk",
    "jaggery(organic)",
    "ground cardamom",
    "almonds(halved)",
    "cashew paste",
    "khaand(a sweetening agent and a healthier substitute of sugar)",
    "flax or chia seeds",
    "plain yogurt",
    "baking soda",
    "vanilla",
    "organic all - purpose flour",
    "toasted almonds",
    "blueberries",
    "corn flakes",
    "mustard seeds",
    "turmeric powder",
    "black pepper powder",
    "ajwain",
    "papaya",
    "fresh lime(juiced)",
    "watermelon balls or small squares(seedless)",
    "fresh pineapple chunks",
    "coconut(unsweetened)",
    "vanilla flavoured yogurt(low fat)",
    "raw papaya",
    "french bean diamond",
    "cherry tomato",
    "crush mix chilli",
    "somtam dressing",
    "peanuts(crushed)",
    "peanuts",
    "milk(whole fat or skimmed)",
    "vegetable oil",
    "extra butter(for crisping the crepe)",
    "spinach",
    "feta cheese (crumbled)",
    "greek yogurt (whisked)",
    "for the cous cous:",
    "plain couscous",
    "extra virgin olive oil",
    "herbs (basil",
    "thyme",
    "cilantro work best)",
    "for the ratatouille:",
    "olive oil (regular not extra virgin)",
    "red onions",
    "aubergines (cut in to 3 cm cubes)",
    "zucchini (cut in to 3 cm cubes)",
    "ground cumin",
    "sweet paprika",
    "tomato paste",
    "potato (boiled)",
    "egg",
    "refined flour (for rolling)",
    "dried breadcrumbs (for rolling)",
    "popped amaranth seeds",
    "jaggery",
    "almonds (slivered",
    "unpeeled)",
    "green gram (dhuli moong dal)",
    "kiwis",
    "coconut cream",
    "bay leaves",
    "coriander seeds",
    "black peppercorns",
    "medium onion",
    "curry powder",
    "fresh coriander sprigs",
    "frozen mixed berries",
    "ripped banana",
    "fresh orange juice",
    "low fat curd",
    "banana",
    "seeds (facseeds and chia seeds)",
    "ginger-garlic paste",
    "peppermint",
    "chili flakes",
    "olive oil (to cook)",
    "button mushroom",
    "wild mushroom",
    "white wine",
    "sage leaf",
    "red poha",
    "truffle oil",
    "rosemary",
    "iceberg lattoos",
    "lolo rosso",
    "endive lettuce",
    "red cabbage",
    "lotus root",
    "kaddu",
    "yam beans",
    "small onions",
    "pomegranate",
    "chalet oil",
    "pomelo",
    "lemongrass sauce",
    "sweet potato cubes",
    "coconut",
    "knoia(ripe)",
    "cashew",
    "pepper powder",
    "caen",
    "cassia",
    "corn kernels",
    "paprika",
    "raw mango(pieces)",
    "celery stock(pieces)",
    "cherry tomatoes",
    "pineapple(pieces)",
    "pasarley",
    "green coriander",
    "badge leaves",
    "black olive",
    "black salt",
    "white pepper powder",
    "taco shell",
    "quick cooking oats",
    "cumin",
    "tomatoes",
    "carrots",
    "green peas",
    "coriander leaves",
    "seedless dates",
    "cashew nuts",
    "dry coconut",
    "poppy seeds",
    "gram flour(besan)",
    "semolina(rava / sooji)",
    "beetroot colour or two oven cooked beetroot paste",
    "oil(for frying)",
    "for sugar syrup: ",
    "cashews(kaju)",
    "white pomfret fish",
    "sunflower refined ooil",
    "lemon(juiced)",
    "coriander powder",
    "garam masala",
    "green chilli",
    "coriander",
    "dry red chillies",
    "fenugreek seeds",
    "boneless chicken",
    "curd",
    "for cooking chicken: ",
    "tamarind pulp",
    "ginger(1 inch)",
    "crushed jaggery",
    "dosa batter(for 4 dosas)",
    "processed cheese",
    "ghee or oil(to crisp the dosa)",
    "curry leaves(deep fried)",
    "zeera powder",
    "buns",
    "all purpose white flour",
    "dry yeast",
    "warm water",
    "sesame oil",
    "worcestershire sauce",
    "aromat powder",
    "millet flour",
    "tapioca flour",
    "soy milk",
    "garlic powder",
    "tomato sauce",
    "mozzarella cheese",
    "prosciutto",
    "pepperoni",
    "chicken salami",
    "salami milano",
    "spring onion",
    "soya sauce",
    "oyster sauce",
    "oil(for greasing)",
    "pizza dough(2 boules)",
    "red pepper",
    "basil pesto(purchased",
    "homemade or vegan pesto)",
    "kosher salt",
    "pork chop",
    "pink pepper corn",
    "green pepper corn",
    "aromatic sauce",
    "salted butter",
    "bell pepper chop",
    "apricot",
    "red wine",
    "ancho chilli",
    "cayenne pepper",
    "microgreen",
    "brown sugar",
    "chocolate",
    "chocolate chips",
    "cocoa powder",
    "for chicken parmigiana: ",
    "chicken breast",
    "egg whole frozen",
    "planko bread crumbs",
    "fresh italian parsley",
    "solid butter unsalted",
    "italian parmesan cheese",
    "for pepperonata: ",
    "green pepper",
    "yellow pepper",
    "fresh tomato",
    "butternut squash",
    "pure olive oil",
    "black pepper corn(crushed)",
    "for garnishing: ",
    "parsley sprig",
    "rice",
    "vanilla extract",
    "cinnamon powder",
    "unsweetened cocoa powder",
    "norwegian salmon",
    "black garlic pickle",
    "butchery bag",
    "smoked yogurt",
    "home made prawn crisp",
    "edible flower",
    "filo pastry",
    "himalayan salt",
    "green zucchini",
    "yellow zucchini",
    "capsicum yellow",
    "capsicum green",
    "capsicum red",
    "pizza spice mix",
    "desi ghee",
    "black cardamom seeds",
    "chocolate block",
    "pistachio",
    "jamun",
    "chilli",
    "cumin(powdered)",
    "fish fillet (pomfret(or any white fish)",
    "semolina",
    "wilted spinach",
    "chicken(boneless",
    "cube size)",
    "chesse",
    "green chilli paste",
    "cream(fresh)",
    "kaju paste",
    "king fish cut into one inch pieces",
    "paprika cut into one inch pieces",
    "bezel pasto",
    "white wine vinegar",
    "cooking spray",
    "red lentils or masoor dal(half - boiled)",
    "potato(grated)",
    "french beans",
    "bread slices",
    "ground chickpea flour(sattu)",
    "corn flour",
    "besan",
    "bread crumbs for crunchyness",
    "refined oil(for fryingp)",
    "for modak: ",
    "semolina(rava / suji)",
    "active charcoal",
    "beetroot puree",
    "tossed flax seeds(for topping)",
    "green cardamom powder",
    "nutmeg powder",
    "for gujiya pastry: ",
    "for gujiya stuffing: ",
    "dark chocolate",
    "prunes",
    "mawa",
    "all - purpose flour",
    "clarified butter(ghee)",
    "white chocolate",
    "dessicated coconut",
    "full cream milk",
    "cream",
    "mascarpone",
    "paan(crushed)",
    "cookie crumble",
    "dark chocolate(melted)",
    "caramel sauce",
    "bread crumb",
    "jalapeno",
    "jeera powder",
    "maida",
    "cottage cheese",
    "for thousand island dressing: ",
    "mayonnaise",
    "tomato ketchup",
    "minced garlic",
    "white butter",
    "breakfast sugar",
    "milk full fat",
    "winter carrots",
    "cashew nuts(crushed)",
    "full fat milk",
    "grain sugar",
    "greek yogurt",
    "heavy cream",
    "pure maple syrup",
    "1 cucumber peeled and chopped",
    "garlic buds",
    "pepper(freshly picked)",
    "whisky",
    "star anise",
    "cloves",
    "green apple",
    "powdered sugar",
    "red wine (merlot / zinfandel)",
    "apple cider",
    "orange(zested and juiced)",
    "cloves(whole)",
    "green cardamom",
    "cinnamon sticks",
    "anise(whole)",
    "brandy",
    "haldi",
    "ground white pepper(kali mirch)",
    "assam tea bags",
    "almonds(badam) - coarsley crushed",
    "poppy seeds(khus - khus)",
    "fennel seeds(saunf)(crushed coarsely)",
    "cardamom(elaichi) powder",
    "ground sugar",
    "saffron(kesar) strands",
    "vanilla infused tequila",
    "vanilla liqueur",
    "lime juice",
    "artichoke hearts(cubed)",
    "polenta",
    "pepper(freshly ground)",
    "beetroots",
    "black peppercorns(crushed)",
    "mixed dried herbs",
    "fresh cream",
    "parsley sprigs",
    "red chilli flakes",
    "soup sticks as required",
    "rum",
    "espresso",
    "sugar syrup / gur(jaggery) syrup",
    "green cardamom pod",
    "",
    "chamomile tea bags",
    "berries",
    "boiling water",
    "soybean",
    "hot water",
    "freshly ground coffee",
    "coffee powder",
    "almonds(whole)",
    "bayleaf",
    "chicken broth",
    "egg yolk",
    "white bread slices",
    "whole turkey",
    "crumbled sage and thyme",
    "garlic minced",
    "balsamic vinegar",
    "cranberry",
    "whole chicken",
    "butter(to rub)",
    "extra olive oil",
    "turnip",
    "beetroot",
    "chipotle powder",
    "boneless skinless chicken thigh(trimmed)",
    "yogurt",
    "chilli powder",
    "oil to fry",
    "peri peri sauce",
    "potato fries",
    "chicken(boneless)",
    "corn flour or all purpose flour",
    "bread crumbs",
    "onion powder(optional)",
    "red chilli powder or paprika or cayenne pepper",
    "oil for deep frying",
    "cooking oil",
    "whole chicken (skin on- rinsed and dressed)",
    "onions (quartered- skin on)",
    "garlic (halved - skin on)",
    "carrots (roughly quartered)",
    "dunkleweizen (pour into a glass and keep open at room temperature for an hour or two to make flat)",
    "chicken stock",
    "malabar peppercorn",
    "cinnamon stick",
    "green cardamom pods",
    "fennel seeds",
    "vermicelli",
    "shahi jeera",
    "saffron",
    "garlic paste",
    "chicken (dark meat)",
    "ginger paste",
    "roma tomatoes (de-seedeed)",
    "boneless chicken thigh (without skin)",
    "black pepper (crushed)",
    "bread crumbs / semolina",
    "chicken drum sticks/ chicken breast",
    "traditional corn syrup (substitution honey)",
    "cheong ju (clear rice wine similar to japanese sake)",
    "green onion",
    "sesame seeds (optional)",
    "for marinating sauce:",
    "gochugaru (red chili pepper flakes)",
    "alapenos",
    "korean pear (substitution asian pear)",
    "spicy yellow mustard",
    "mul yut (substitution honey)",
    "chicken (small pieces)",
    "onion (thin slices)",
    "mustard",
    "bedki chillies",
    "kashmiri chilies",
    "turmeric",
    "lamb mince",
    "pomodaro tomatoes",
    "shallots",
    "bay leaf",
    "yellow chilli powder",
    "cilantro",
    "chicken thigh",
    "fenugreek leaves",
    "broken cashew",
    "kasoori methi",
    "black cardamom",
    "ginger powder",
    "onion powder",
    "oregano",
    "chillil flakes",
    "basil",
    "chicken drumsticks",
    "bread crumbs (as required)",
    "chicken",
    "aromatic powder",
    "filo sheets",
    "mustard oil",
    "kalonjee",
    "saunf",
    "peppercorn (crushed)",
    "mint",
    "onion paste",
    "chicken leg pieces",
    "fresh breadcrumbs",
    "parmesan cheese",
    "fresh parsley leaves",
    "plain flour",
    "chicken breast supremes",
    "sour cream",
    "fresh chives (dried if fresh not available)",
    "fresh parsley (dried if fresh not available)",
    "red onion (optional)",
    "ground black pepper",
    "dahi",
    "cornflour",
    "red chilli sauce",
    "green chilli sauce",
    "capsicum",
    "chicken breast (cut into strips)",
    "fried mixed herbs (italian herb)",
    "chicken (diced))",
    "chicken thigh/breast (cut crosswise into 1/2-inch-thin strips)",
    "sesame oil (toasted)",
    "white pepper (finely ground)",
    "ginger juice",
    "peanut oil or vegetable oil (divided)",
    "snow peas (trimmed)",
    "red bell pepper (cut into thin strips)",
    "rice vinegar",
    "dark soy sauce",
    "chinese rice wine",
    "biryani masala",
    "coconut oil",
    "cauliflower",
    "coconut (diced)",
    "onion (diced)",
    "peppercorns",
    "cardamoms",
    "dry chilli flakes",
    "garlic (crushed)",
    "fresh ginger (peeled)",
    "dry red chilli",
    "green chillies(slit open)",
    "coriander leaves/cilantro",
    "fresh yogurt/curd(beaten)",
    "chicken (cut into pieces)",
    "yogurt/curd",
    "crush black pepper",
    "fresh thyme",
    "low fat milk",
    "basil-tomato sauce",
    "carrot (finely diced)",
    "onion (finely diced)",
    "celery (finely diced)",
    "fresh thyme sprigs",
    "whole free range chicken",
    "parsley stems",
    "celery leaves",
    "lemon slices (1/8 inch thick)",
    "fresh lemon juice",
    "chicken stock/broth",
    "plums (cut)",
    "fresh cherries",
    "chicken breasts",
    "olives",
    "jalapenos",
    "bell peppers(all 3)",
    "thyme dried",
    "black pepper (crushed to taste)",
    "mozerella cheese",
    "chicken wings without skin",
    "hung curd",
    "sweet paprika powder",
    "english mustard paste",
    "bbq sauce",
    "chicken (boneless and cut into small pieces)",
    "eggs (lightly whipped)",
    "ginger garlic",
    "chicken thai",
    "brockley",
    "mushroom",
    "seasonings",
    "chicken leg",
    "fresh chilli",
    "red chili paste",
    "tomato catchup",
    "yellow capsicum",
    "kasundi (bengali mustard sauce)",
    "sweet potato",
    "red and yellow capsicum",
    "ginger and garlic paste",
    "shitake mushrooms",
    "bomb shoots(boiled)",
    "broth powder",
    "shocking wine",
    "potato starch",
    "chicken(sliced)",
    "lemon pieces",
    "onion rings",
    "chicken(sliced ?? into large pieces)",
    "cranberry puree",
    "gram flour",
    "chicken breast(cut 20 strips",
    "20 grams)",
    "all purpose flour",
    "hot red chillies",
    "bread crumbles",
    "white cabbage slaw",
    "pasarley sprig",
    "honey - mustard dip",
    "green bell pepper",
    "chicken thais",
    "thai ginger",
    "lemon leaves",
    "lemongrass",
    "coconut milk powder",
    "red curry paste",
    "bezel leaves",
    "lotus stem",
    "yellow butter",
    "green capsicum",
    "kewda water",
    "cheese",
    "rock salt",
    "processed crab meat",
    "kashmiri chilli powder",
    "chop masala",
    "turkey breast",
    "cajun spice",
    "spinach leaves(cooked and drained)",
    "garlic pods",
    "feta cheese",
    "bacon strips",
    "for cajun spice: ",
    "seasoning salt",
    "red pepper flakes(if you like it spicy)) ",
    "lamb(minced)",
    "couscous",
    "scallion",
    "ao nori herb",
    "five spice",
    "lamb",
    "stock",
    "dry sherry",
    "bokchoy",
    "shitake mushroom",
    "red chilli whole",
    "chilli flakes",
    "black cardamoms",
    "mace",
    "black pepper corn",
    "mutton curry cut",
    "brown onion paste",
    "kashmiri red chili powder",
    "mutton chops",
    "pink peppercorns(crushed)",
    "mutton(wash and cut into very small cubes)",
    "ghee or oil",
    "potatoes",
    "lang shanks",
    "celery stick",
    "lamb stock",
    "tomata puree",
    "lamb pieces",
    "red chili powder",
    "sear fish",
    "pureed tamarind",
    "powdered turmeric",
    "sole fillet(you can also do 2 / 3 types of fish) ",
    "large shrimps(optional)",
    "potatoes(peeled)",
    "onions(cut into slices)",
    "red capsicum(can use green also)",
    "parsley or coriander(choose the herb that most suits your taste buds)",
    "few dashes of hot sauce",
    "whole coriander seeds",
    "whole red chilli",
    "curry leaf",
    "coconut milk",
    "seabass fish curry cuts",
    "tamarind",
    "tamarind(lemon sized)",
    "lobster(de - shell and devein and make a small cube)",
    "salt and lime",
    "surmai",
    "tabasco",
    "salmon fillet",
    "lobster shell",
    "leeks",
    "peppercorn",
    "lobster meat",
    "arborio rice",
    "lobster stock",
    "parmesan",
    "sea bass fillets",
    "olive oil(for grilling)",
    "red wine vinegar",
    "garlic clove",
    "bamboo skewers",
    "baked tart of mixed sea food served with phyllo fruit bowl",
    "savory tart shell(semi baked)",
    "mixed sea food",
    "mornay sauce",
    "assorted herb and seasoning",
    "phyllo pastry",
    "assorted seasonal fruit",
    "prawns",
    "gherkin",
    "mix bell pepper",
    "tiger milk",
    "sweet corn",
    "green lemon juice",
    "coriander stems",
    "celery stalks",
    "cooked rice",
    "shrimp(de - veined",
    "cooked green peas",
    "egg(scrambled)",
    "vegetable oil / butter",
    "jeera whole",
    "kashmiri chilly",
    "kokum",
    "asafoetida",
    "goan rice",
    "hing",
    "basmati rice",
    "lecite",
    "rohu fish",
    "whole red chillies",
    "river sole fish(cut in thin strips)",
    "beer",
    "prawns(shelled and cleaned)",
    "spring onions",
    "mango flesh",
    "litchis(deseeded)",
    "lemon(for lemon juice)",
    "peanuts(to garnish)",
    "white fish(cut into cubes)",
    "fresh green chillies(deseeded)",
    "fresh coconut paste",
    "red chilli paste",
    "whole dry red chillies",
    "black mustard seeds",
    "tamarind extract",
    "white wine and water mix to cover",
    "black pepper corns",
    "tomatoes(peeled and seeded)",
    "spring fresh thyme - optional 1 bay leaf",
    "wine vinegar",
    "prepared mustard",
    "assorted garden herbs(parsley",
    "basil etc.",
    "bacon",
    "sweet chili sauce",
    "baked rice",
    "fish",
    "reshagi red chilli powder",
    "fillet fish",
    "for fish pieces(boneless)",
    "sauce: ",
    "chili sauce",
    "tuna",
    "fenugreek",
    "whole chilli",
    "pandan leaf",
    "red chilli",
    "gorca",
    "surmai fish",
    "ginger(mash)",
    "fennel",
    "whole coriander",
    "red pepper powder",
    "lemon pieces of",
    "basa fish",
    "fresh fish pieces(river sol or sea bass)",
    "passerley",
    "egg(optional)",
    "soda water",
    "king fish",
    "ripe tomatoes",
    "fennel powder",
    "sol fish",
    "potato",
    "red rice vermicelli / broken sooji / semolina vermicelli",
    "saffron strands / thread",
    "english cucumbers",
    "romaine lettuce",
    "big lemon",
    "fresh turmeric",
    "lemon grass",
    "hot curry powder",
    "pineapple chunks",
    "fresh pineapple",
    "carnaroli rice",
    "vegetable broth",
    "parmigiano cheese",
    "onion(minced)",
    "salt & pepper",
    "chana dal",
    "urad dal",
    "beans",
    "soya chunks",
    "american corn kernels",
    "cumin seed",
    "pepper corn",
    "bell pepper(saut ? ed and diced)",
    "zucchini",
    "fenugreek(methi)",
    "clarified butter(desi ghee)",
    "cumin seeds(jeera)",
    "asafoetida(heeng)",
    "green chilles",
    "cooked basmati rice",
    "mustard seeds(sarson)",
    "curry leaves(kadhi patta)",
    "whole red chilli(sabut laal mirch)",
    "turmeric powder(haldi)",
    "black gram(kala chana)",
    "basmati rice(soaked for 2 hours)",
    "green chillies(slit)",
    "fresh mint leaves",
    "fresh coriander leaves",
    "screw pine essence(kewra)",
    "browned onions",
    "whole wheat flour dough",
    "bell peppers",
    "peas",
    "fish(cubed)",
    "thai green curry paste",
    "ginger / galangal",
    "palm sugar",
    "paneer(cooked)",
    "elaichi",
    "garlic flakes",
    "chalet",
    "water chestnuts",
    "leaks",
    "rice baked",
    "white chillies",
    "rice wine vinegar",
    "small bunch pasarley",
    "jasmine rice(baked)",
    "edamame beans",
    "mock meat",
    "sunflower oil",
    "mix vegetable",
    "steamed rice",
    "red rice",
    "raw banana",
    "drumstick",
    "small raw mango",
    "sour curd",
    "bean stick",
    "mustard seeds(crushed)",
    "big cardamom",
    "lamb bonz",
    "royal cumin",
    "baguette(grilled slices)",
    "black olive tapenade",
    "artichoke hearts",
    "lettuce arugula(trummed)",
    "tomato confit",
    "fresh basil leaves",
    "goat cheese",
    "parmesan cheese shavings",
    "mozzarella buffalo cheese",
    "fresh buffalo mozzarella cheese",
    "canned pelati tomatoes(cooked)",
    "pizza / flatbread base",
    "mushrooms",
    "garlic cloves(halved)",
    "egg yoks",
    "double cream",
    "yolk",
    "gelatine",
    "pistachio paste",
    "strawberry",
    "pizza base",
    "pizza sauce",
    "rava / suji / semolina",
    "fresh coconut(pieces)",
    "jeera",
    "dhaniya",
    "ghee / clarified butter",
    "cookes peas",
    "bread",
    "bread(white / brown)",
    "for chana chaat: ",
    "chana",
    "chana masala",
    "panko",
    "1 / 4 cup plus 1 tablespoon extra - virgin olive oil",
    "plus more for drizzling",
    "freshly ground pepper",
    "manila clams or cockles",
    "scrubbed",
    "dry white wine",
    "spaghetti",
    "mullet bottarga(optional; see note) ",
    "kasha",
    "buckwheat flour",
    "all - purpose gluten free flour",
    "xanthum gum",
    "buttermilk",
    "whole wheat flour",
    "ham slices",
    "brown bread slices",
    "salt and black pepper",
    "aamchoor powder",
    "anardana",
    "kasuri methi",
    "avocado",
    "pizza tasting",
    "french bread loaf",
    "stuffed green olive",
    "vanilla essence",
    "poppy seed",
    "lemon peel",
    "to serve: ",
    "lemon syrup",
    "whip cream",
    "fresh berry",
    "milk chocolate or dark chocolate",
    "almonds and pistachios",
    "grapes",
    "kiwi",
    "tortilla sheet",
    "broken rice",
    "egg yolks",
    "whipped cream",
    "vanilla pod",
    "mandarin",
    "flax seeds",
    "chocolate sponge eggless",
    "single cream",
    "instant coffee powder",
    "dark rum",
    "vanilla pre mix",
    "gel",
    "yeast",
    "cinnamon molasses powder",
    "nutmeg(powdered)",
    "orange peel",
    "powdered cinnamon",
    "milk or water",
    "camel milk",
    "knoia(cooked)",
    "brown sugar or jaggery",
    "nuts",
    "coconut nuts",
    "kinoia",
    "maple syrup",
    "pot barley",
    "thick mutton chunks",
    "thick neck of lamb chops",
    "water or stock (to cover)",
    "black pepper (freshly ground)",
    "shallow fried chicken",
    "bottle gourd (boiled and sun dried)",
    "whole spices:",
    "deggi mirch",
    "fennel seeds powder",
    "dry ginger powder",
    "for berry parfait:",
    "caster sugar",
    "berry puree",
    "cream cheese",
    "for hazelnut streusel:",
    "ground hazelnut",
    "for hazelnut white chocolate pressed sable:",
    "hazelnut streusel",
    "cocoa butter",
    "puffed rice",
    "clarified butter",
    "melted white chocolate",
    "for flexy berry:",
    "raspberry puree",
    "liquid glucose",
    "pectin",
    "raw potato",
    "pineapple",
    "mix vegetable (tomatoes",
    "peas and french beans)",
    "strawberries",
    "cauliflowers",
    "halved",
    "dijon mustard",
    "lemon wedges",
    "sweet potatoes",
    "pure vanilla extract",
    "ground cinnamon",
    "himalayan pink salt / rock salt",
    "tart apples (2 large)",
    "apple juice",
    "vanilla extracts",
    "apple pie spice (cinnamon)",
    "pecans",
    "candied red cherries (halved)",
    "candied green cherried (halved)",
    "candied pineapple (diced)",
    "cashews (optional)",
    "egg whites",
    "almond powder",
    "matcha powder",
    "popped amaranthus (cholai)",
    "sunflower seeds",
    "sesame seeds",
    "plain yogurt (whipped with lemon rind)",
    "dark chocolate coverture",
    "rice paper sheets",
    "iceberg lettuce",
    "bean sprouts",
    "cucumber",
    "tofu",
    "rice noodles (soaked in warm water for 20-25 minutes)",
    "hoisin sauce",
    "yams (red skinned)",
    "condensed milk",
    "marshmallows",
    "asparagus",
    "1 fried onion (medium)",
    "1/2 tsp breakfast sugar",
    "10 ml potato starch",
    "20 ml stock vegetarian",
    "20 gm porcini",
    "salt to taste",
    "50 ml oil",
    "rolled oats",
    "buttermilk (divided)",
    "whole wheat flour or oat flour",
    "canola oil",
    "honey or maple syrup",
    "butter biscuits (broken into pieces)",
    "cream cheese (softened)",
    "rose essence or vanilla essence",
    "egg yolks + whole eggs",
    "maida/ flour",
    "butter (softened",
    "salted. in case you are using unsalted butter",
    "add 1/4 tsp salt)",
    "milk (to make the batter smooth. adjust the milk quantity according to your batter's smoothness)",
    "coffee powder + 1 tsp water",
    "to make a paste (you can increase or decrease according to your coffee tolerance)",
    "olive or sunflower oil",
    "rashers lean bacon",
    "onions or shallots (cut in half)",
    "boneless and skinless chicken breasts (chopped into 3cm pieces)",
    "chicken or vegetable stock",
    "fresh thyme sprigs (washed or 1/2 tsp dried thyme)",
    "christmas mix spicy",
    "glucose",
    "poultry flour",
    "bread flour",
    "oven temperature",
    "jaggery sugar",
    "oven temp: 150 c-300 f",
    "mixed fruits (sultanas",
    "candied peels and cherries)",
    "cadbury gems",
    "paneer (cottage cheese)",
    "coriander leaves (chopped)",
    "malai or cream",
    "raisins and cashew nuts",
    "cashew nuts paste",
    "kitchen king masala",
    "kasuri methi (dry fenugreek)",
    "cardamom seeds",
    "lamb chops or stewing lamb",
    "cassia bark or cinnamon stick",
    "ground coriander",
    "fresh sole fish",
    "raw rice",
    "ginger (large)",
    "clove powder",
    "ground nut oil",
    "tamarind paste",
    "rice (washed)",
    "almonds (shredded)",
    "green cardamoms(powdered)",
    "rose water",
    "rose petals (dried)",
    "yogurt (strained)",
    "milk (warm)",
    "cheddar cheese",
    "eggs (separated)",
    "cream of tarter",
    "butter (at room temperature)",
    "dark brown sugar",
    "all spice powder",
    "currants; golden raisins; dark raisins (each)",
    "soft dried figs",
    "prunes (stoned dried)",
    "apricots (dried)",
    "almonds (chopped)",
    "instant espresso (mixed with 1 tbsp water)",
    "chicken breasts (boneless)",
    "eggs (slightly whisked)",
    "ground pimento",
    "vodka",
    "asparagus spears(cooked)",
    "ham",
    "pineapple slices",
    "mixed vegetables - chopped fine or grated",
    "eggs (slightly beaten)",
    "cornflour (blended with water)",
    "ajinomoto (optional)",
    "chicken legs",
    "lime (halved)",
    "jerk seasoning powder (bottled)",
    "jerk seasoning paste (bottled)",
    "poppy",
    "wiped cream",
    "sevaiyan",
    "quinoa",
    "dried figs",
    "almond milk",
    "melon seeds",
    "kasturi methi",
    "nuscovado sugar (you can also use normal sugar)",
    "cashew nuts and almonds",
    "red grapes",
    "ragi flour",
    "oats flour",
    "dates (ripe)",
    "white sesame seeds",
    "coconut powder",
    "rose water (infused with 4-5 strands of saffron)",
    "coriander seed powder",
    "rose petal powder",
    "black cardamom powder",
    "cream/malai",
    "finger millet flour (ragi)",
    "pepper whole",
    "fresh bhang leaves",
    "bhang seed powder",
    "fresh green chilly",
    "red chilly powder",
    "soda",
    "kuttu atta",
    "mozzarella cheese fresh",
    "arbi / colocasia roots",
    "water chestnut flour(kuttu ka aata)",
    "carom seeds",
    "kewda to flavor",
    "one can of sweetened condensed milk",
    "ice cold water",
    "instant vanilla pudding mix",
    "cream cheese(softened and cut into 8 pieces)",
    "one 9 x 13 inch layer of red velvet cakcake",
    "ripe bananas",
    "mini chocolate chips",
    "cocoa",
    "cake flour",
    "butter(room temp cut into 1 inch pieces)",
    "cider vinegar",
    "red food coloring",
    "unsalted butter(room temperature)",
    "digestive biscuits",
    "egg(lightly beaten)",
    "egg white powder",
    "hazelnut powder",
    "hazelnut(toasted)",
    "yellow cornmeal",
    "buttermilk(well - shaken)",
    "cheddar(extra sharp)",
    "scallion(white and pale green parts only)",
    "pickled jalapenos(drained)",
    "brioche loaf",
    "avocado paste",
    "phyllo pastry sheet",
    "assorted seasonal fruits",
    "hollandaise sauce",
    "coffee",
    "fresh corn kernels",
    "whole egg",
    "jalapeno poppers",
    "smoked paprika",
    "coriander(toasted & ground)",
    "lemon(zest and juice)",
    "basmati rice(soaked in water)",
    "butter(chilled)",
    "chilled water",
    "dough tortia",
    "refried beans",
    "bell paper",
    "lettuce",
    "orange cheddar cheese",
    "chitpole dressing",
    "for pico de chelo",
    "black beans (boiled )",
    "vine paper",
    "core",
    "chopped and sliced ??apple",
    "chopped and sliced ??pears",
    "castor or powdered sugar",
    "butter or margarine",
    "vip cream",
    "vanilla bean",
    "gelatin",
    "mixed boiled beans (choose from rajma",
    "chawli",
    "chick peas",
    "hara chana)",
    "tomatoes (diced)",
    "for garnish:",
    "fresh coriander",
    "raw banana paste",
    "phyllo sheets",
    "coconut (tender)",
    "ripe mango (diced)",
    "dry fruits",
    "cantaloupe",
    "kiwifruiit",
    "marshmallow",
    "mint leaf (crushed nuts",
    "sesame seeds or cinnamon)",
    "noodles",
    "egg (slightly beaten)",
    "orange essence",
    "strawberries (to garnish)",
    "brown slice bread",
    "emmental cheese",
    "pasta (of your choice)",
    "lamb keema",
    "eggs (hard boiled peel)",
    "panco",
    "peanut oil",
    "apple cedar vinegar",
    "english mustard",
    "paprika and olive powder",
    "fish with curry",
    "ginger and garlic",
    "mughalai delecacy",
    "acorn squash",
    "sage",
    "peeled ginger",
    "lightbrown sugar",
    "honeydew melon",
    "avacado",
    "scallions",
    "cloves of garlic",
    "cabbage kimchi",
    "boneless steak",
    "cooking wine",
    "kimchi",
    "dried appricots",
    "milk dried plumps",
    "black berries",
    "lamb leg",
    "corriender",
    "pork tenderloin",
    "red pepper flake",
    "red wine vineger",
    "ricotta",
    "morel mushrooms",
    "fresh peas",
    "shallot",
    "boneless lamb",
    "corriender powder",
    "giner",
    "prawn",
    "teriyaki sauce",
    "salmon",
    "thai basils",
    "rice noodles",
    "beef",
    "rice paper",
    "peanut sauce",
    "spice chicken",
    "pickled carrort",
    "mayo",
    "bean curd",
    "mix herbs",
    "cucuber",
    "rice noodle",
    "vegatable soup",
    "chicken brouth",
    "meaty sparerib",
    "sesame - cilantro rice",
    "green beans",
    "black paper",
    "vineger",
    "crab",
    "lecttus",
    "paper",
    "panner",
    "ketchup",
    "viniger",
    "indian spices",
    "cinamon",
    "yougurt",
    "cicken",
    "tandori spices",
    "lime",
    "shrimp",
    "pasley",
    "thyme leaves",
    "red papper flakes",
    "vegetable stock curry",
    "lime leaves",
    "raddish",
    "pork",
    "coriender",
    "pickeled carrot",
    "crunchy noodles",
    "dried meat",
    "aall purpose flour",
    "aubergine",
    "spices",
    "green pea",
    "olive",
    "salt papper",
    "chickpeas",
    "nepali spices",
    "bamboo shoot",
    "black eye bean",
    "yello lentils",
    "boiled potatoes",
    "coriender powder",
    "minced lamb marinated with indian spices",
    "lamb ribs",
    "minced chicken meat",
    "flour wrapping",
    "black bean",
    "sake",
    "japanese sauces",
    "chilli oil",
    "sichuan pepper",
    "chillies",
    "ginger onion",
    "thai sauces",
    "penut",
    "minced pork",
    "fish sauce",
    "black peper",
    "sesame seed",
    "boiled egg",
    "tumeric powder",
    "stir fried eggs",
    "seaweed",
    "korean sauce",
    "japanes curry sauce",
    "spinich",
    "gochujang",
    "capcicum",
    "squid",
    "fish ball",
    "fish cake",
    "mussels",
    "crab sticks",
    "red pepper flakes",
    "penuts",
    "fresh sage",
    "bone-in pork shoulder",
    "ground pepper",
    "brown rice",
    "squash",
    "sichuan peppercorns",
    "ground lamb",
    "spicy aioli",
    "corn",
    "mushrooms lemon zest",
    "roasted almonds",
    "roasted peanuts",
    "thai chillies",
    "vermicelli noodles",
    "asaian eggplat",
    "sliced shallots",
    "purpose flour",
    "chicken thighs",
    "jasmine rice",
    "black sesame seeds",
    "parmigiano-reggiano cheese",
    "jalapeao",
    "radishes",
    "greens",
    "sprouts",
    "summer squash",
    "corn tortilla mix",
    "thinly sliced",
    "littleneck clams",
    "poblano pepper",
    "spanich",
    "fig",
    "mild honey",
    "cayenne",
    "extra-virgin olive oil",
    "coarse sea salt",
    "chopped kimchi",
    "country-style bread",
    "cilantro leaves",
    "poblano chiles",
    "shrips",
    "red salsa",
    "corn tortillas",
    "anchovy fillets",
    "penne pasta",
    "walnut",
];
